language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g gulp
script:
- gulp
deploy:
  provider: npm
  email: sh19910711@gmail.com
  api_key:
    secure: "OcSfxiEgF0/VDURZkimlheBCBwbGaSpKYK3vBXj4EbiIUy/e8+eCLxhOK3w1C17bSSQSVqsD27f3YoUlECwtMZqxz33lJMEicP0L31ozndVny5DOm0Yar84A2iwo7yn+k2IqyC2UG9/owK0Y5JnLvUdgft7eSMBgFdnmhlEAlQw="
  on:
    tags: true
    repo: sh19910711/phantomochajs
